### ISSUE TITLE
Support for EBS Volume key migration

### ISSUE THREAD

**Issue by jeffe** [jbrt/ec2cryptomatic#15]
When you attempt to run against an already encrypted EBS volume the current output is "This volume is already encrypted nothing to do with this one" 
From [Amazon's documentation](https://aws.amazon.com/premiumsupport/knowledge-center/ebs-change-encryption-key/) it looks like the process to migrate/swap key's is fairly similar to the approach for converting unencrypted volumes.

**Comment by jbrt** [comment]
Hello @jeffe 

Good idea, I'll add in the next days a feature for re-encrypting EBS volumes.

**Comment by jbrt** [comment]
Feature added

Regards
