### ISSUE TITLE
No Error / Exit on incorrect KMS key alias

### ISSUE THREAD

**Issue by jeffe** [jbrt/ec2cryptomatic#16]
If you enter a nonexistent/incorrect KMS key alias the application starts, the snapshot is created, but as the key doesn't exist the encryption fails, but for some reason this leads to the application to stalling and never exiting.

**Comment by jeffe** [comment]
I also noticed when I re-run the job with the correct key alias, it uses the existing snapshot it created on the previous run, but it doesn't seem to respect the -d flag on the second run

**Comment by jbrt** [comment]
Hello @jeffe 

Thank you for this error report.
I've added a new security check on the given KMS alias name.

Regards
