### ISSUE TITLE
Docker image fails with cert issue.  ca-certificates need updating

### ISSUE THREAD

**Issue by docwho2** [jbrt/ec2cryptomatic#19]
docker run ec2cryptomatic run -r us-east-1 -i i-XXXXXXXXXXXX
		-=[ EC2Cryptomatic ]=-
2020/11/24 17:31:15 Error with this key: RequestError: send request failed
caused by: Post "https://kms.us-east-1.amazonaws.com/": x509: certificate signed by unknown authority

I was able to make it work now by updating certs in the Dockerfile:

FROM golang:1.14.3-alpine3.11 AS builder
WORKDIR /go/src/github.com/jbrt/ec2cryptomatic  
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ec2cryptomatic .
** RUN apk add -U --no-cache ca-certificates **

FROM scratch  
LABEL maintainer="julien@toshokan.fr"
WORKDIR /app/
COPY --from=builder /go/src/github.com/jbrt/ec2cryptomatic/ec2cryptomatic .
** COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ **
ENTRYPOINT ["./ec2cryptomatic"]
CMD ["--help"]

**Comment by jbrt** [comment]
Hi @docwho2 

Thank you for this feedback. I will try that on my side.
Stay tuned

Regards

**Comment by jbrt** [comment]
Hi again,

I've tested and merged your code.
Thank you for your help !

Have a nice day,
Julien

**Comment by docwho2** [comment]
Thank you !!

Security came down on us and I’m forced to encrypt 100’s of volumes that were all running on instances.  Saved me a ton of manual work !

Have about 20 more servers to go, man does it take time when volumes are greater than 500Gig.  Been working like a champ with 10 docker containers working away on EC2 instances :-)

Steve
Best Buy DevOps

**Comment by jbrt** [comment]
You're welcome ! 
I know that feeling when security team send you a mail with a lot of security requirements... 😁
