### ISSUE TITLE
kms:DescribeKey

### ISSUE THREAD

**Issue by bslavin** [jbrt/ec2cryptomatic#26]
2021/10/19 12:56:32 Error with this key: AccessDeniedException: User: arn:aws:iam::3915824****:user/EC2Cryptomatic is not authorized to perform: kms:DescribeKey on resource: arn:aws:kms:us-west-2:3915824****:key/*****-048e-4be0-b497-ca151cd223c5 because no resource-based policy allows the kms:DescribeKey action.

To fix I modified the policy to include kms:DescribeKey

```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1504425390448",
            "Action": [
                "ec2:AttachVolume",
                "ec2:CopyImage",
                "ec2:CopySnapshot",
                "ec2:CreateSnapshot",
                "ec2:CreateVolume",
                "ec2:CreateTags",
                "ec2:DeleteSnapshot",
                "ec2:DeleteVolume",
                "ec2:DescribeInstances",
                "ec2:DescribeSnapshots",
                "ec2:DescribeVolumes",
                "ec2:DetachVolume",
                "ec2:ModifyInstanceAttribute",
                "kms:DescribeKey",
                "ec2:StartInstances"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}```

**Comment by jbrt** [comment]
Hello @bslavin,

You absolutely right ! 
Thanks for this feedback, I'll update the documentation right now.

Regards

**Comment by tornado67** [comment]
This does not work. IAM is literally worst part of the AWS...
