### ISSUE TITLE
Not working please help

### ISSUE THREAD

**Issue by hirenshah005** [jbrt/ec2cryptomatic#4]
[ec2-user@ip-172-31-35-171 ec2cryptomatic]$ ./ec2cryptomatic.py -r us-east-1 --instances i-069c975b3afc40900
Problem with the instance (An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstances operation: The instance ID 'i-069c975b3afc40900' does not exist)

I have given full permission to the instance.

**Comment by jbrt** [comment]
Hello,

It's strange... It's not related to a credentials problem, I guess.
Obviously I assume that's you've check your instance ID. I will check on my side with a dedicated instance created for this purpose and I go back to you.

**Comment by jbrt** [comment]
Hello again,

I just tried, on one instance with 2 EBS volumes and it's works:

[ec2-user@ip-172-31-54-119 ec2cryptomatic]$ ./ec2cryptomatic.py -r eu-west-1 -i i-0d48bd594c9b4dc9a -ds
Start to encrypt instance i-0d48bd594c9b4dc9a
>Let's encrypt volume vol-08b8b4688f625c6ec
->Take a first snapshot for volume vol-08b8b4688f625c6ec
->Copy the snapshot snap-0256f3ac03356621a and encrypt it
->Creating an encrypted volume from snap-045d1eeba471570be
->Swap the old volume and the new one
->Cleanup of resources
-->Deleting unencrypted volume vol-08b8b4688f625c6ec
->Put flag DeleteOnTermination on volume
>Let's encrypt volume vol-0613bda82eb977532
->Take a first snapshot for volume vol-0613bda82eb977532
->Copy the snapshot snap-05d50d9ec152856ed and encrypt it
->Creating an encrypted volume from snap-05fd45da184c46d33
->Swap the old volume and the new one
->Cleanup of resources
-->Deleting unencrypted volume vol-0613bda82eb977532
->Put flag DeleteOnTermination on volume
-> Starting instance i-0d48bd594c9b4dc9a
-> Instance i-0d48bd594c9b4dc9a started
End of work on instance i-0d48bd594c9b4dc9a

Maybe your instance-id has changed in the meanwhile...

**Comment by hirenshah005** [comment]
Sorry my bad, it got resolved as there was extra char. getting inserted. Thanks for help and this awesome script.

**Comment by jbrt** [comment]
Great, glad to ear that. Thank you for using this script and for your message.
Have a nive day :-)

**Comment by jbrt** [comment]
Hello @hirenshah005 ,

Just for your information I worked on a serverless version of ec2cryptomatic. If you're interest by this, you can find this project here : https://github.com/jbrt/ec2cryptomatic-serverless

Best regards,
