### ISSUE TITLE
Need Start-Instance permission

### ISSUE THREAD

**Issue by dstinebaugh** [jbrt/ec2cryptomatic#5]
Current json on your README page for the IAM role policy, doesn't list the "ec2:StartInstances" option so it errors out on the final step.
![image](https://user-images.githubusercontent.com/6546978/54222207-307ee200-44b2-11e9-93c4-6f76cb15e5e9.png)

**Comment by jbrt** [comment]
Hello,

Thank you for this message, you totally right. Sorry about that.
Fixed.

Regards
