### ISSUE TITLE
io1

### ISSUE THREAD

**Issue by joshdlee** [jbrt/ec2cryptomatic#6]
how do we add iops? i am getting an error for io1 volume types.

**Comment by jbrt** [comment]
Hello,

Sorry for this late answer. Can you please send me the traceback of this error ? 
Currently, you can't specify the needed IOPS for io1 volumes, this isn't implemented. I can add this feature in next weeks.

Regards

**Comment by joshdlee** [comment]
Hi jbrt, 

I lost the error, I will try to look for it. Thank you for your quick reply. io1 support would be fantastic. This is a cool function!!!!

Regards,
Josh

**Comment by jbrt** [comment]
Hi @joshdlee 

I'll add this features in few days (maybe a couple of weeks). I work on another project right now and 
as soon as I can i'll add this into the project.  

Stay tuned,
Regards,

**Comment by jbrt** [comment]
Hi @joshdlee 

I've reproduced the bug on my side. I'll fix it as soon as I can (and simplify the code since AWS has changed the way how we can encrypt volumes).

Stay tuned
Regards,

**Comment by jbrt** [comment]
Hi @joshdlee 

I've published a new version of the script. This new version fix the problem related to io1 volumes.
Can you please test on your side ?

Regards

**Comment by jbrt** [comment]
@joshdlee did you have the time to test the new version of the script ? 
Let me know if it's works for you.
