### ISSUE TITLE
Skip AWS reserved tags

### ISSUE THREAD

**Issue by oleksey** [jbrt/ec2cryptomatic#8]
I believe it would be a good idea to skip AWS reserved tags: 
```
aws:cloudformation:logical-id
aws:cloudformation:stack-id
aws:cloudformation:stack-name
```

The program fails to copy those tags:

```
- Let's encrypt volume vol-0x62617a696e6761
-- Take a snapshot for volume vol-0x62617a696e6761
-- Creating an encrypted volume from snap-0x776861742773207570
Problem with the instance (An error occurred (InvalidParameterValue) when calling the CreateTags operation: Value ( aws:cloudformation:stack-name ) for parameter key is invalid. Tag keys starting with 'aws:' are reserved for internal use)
```

**Comment by jbrt** [comment]
Hello,

Thank you for this feedback. You right, i'll working on it and fix that.
Stay tuned.

**Comment by jbrt** [comment]
Hello @oleksey 

I released a new version with a fix for this problem of tags copying (and I've also raised the maximum number of retries).

Can you check again please and send me a feedback ?

Regards

**Comment by oleksey** [comment]
Hey, 

Looks like it still tries to copy AWS reserved tags:

oleksey@LTPC04UB4L:~/ec2cryptomatic$ ./ec2cryptomatic2.py -r eu-central-1 -i i-061432cc49c56340e

Start to encrypt instance i-061432cc49c56340e
- Let's encrypt volume vol-0c877a4df0a28b5af
-- Take a snapshot for volume vol-0c877a4df0a28b5af
-- Creating an encrypted volume from snap-03c2b3cc5fd4e0f24
Problem with the instance (An error occurred (InvalidParameterValue) when calling the CreateTags operation: Value ( aws:cloudformation:stack-name ) for parameter key is invalid. Tag keys starting with 'aws:' are reserved for internal use)

oleksey@LTPC04UB4L:~/ec2cryptomatic$ ./ec2cryptomatic2.py --version
1.2.2

**Comment by jbrt** [comment]
Hello @oleksey 

You right, my tests was not relevant. 
I've tested again and found the problem (tested with a CFN template with extra volumes and tags). 
 It works now, can you please check with the version 1.2.3 ?

Regards,

**Comment by jbrt** [comment]
Hello,

I found the problem (problem with my previous test).
Can you try with version 1.2.3 ?

Regards
Julien

**Comment by oleksey** [comment]
I confirm that it works now. AWS tags were successfully skipped.

**Comment by jbrt** [comment]
Great ! Thanks for your feedback
